ZSH=$HOME/.oh-my-zsh
ZSH_THEME="agnoster"

plugins=(git colored-man-pages)

export EDITOR='vim'

DISABLE_UPDATE_PROMPT=true
source $ZSH/oh-my-zsh.sh

if [[ "$(uname -s)" == "Linux" ]]; then
  eval `dircolors ~/.dircolors.256dark`;
else
  export LSCOLORS='ExFxBxDxCxegedabagacad'
fi

source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zsh/zsh-syntax-highlighting/zsh-syntax-hightlighting.zsh

# Explicity bind home and end keys (in case of terminal compatibility issues)
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line

# Use 256 color for tmux.
alias tmux="TERM=screen-256color-bce tmux"
if [[ -z "$TMUX" ]]; then
  export TERM="xterm-256color"
fi

if [[ -f ~/.zshrc.local ]]; then
  source ~/.zshrc.local
fi
